### ISSUE TITLE
Footprint field

### ISSUE THREAD

**Issue by adzenith** [HashDefineElectronics/KiCad_BOM_Wizard#2]
Thanks for the plugin! Is there any chance you'd be able to add the ability to output the footprint field as well? I tried `ROW_PART_FOOTPRINT` but it didn't work, and I didn't see another way to output the footprint.
Thanks!

**Comment by HashDefineElectronics** [comment]
Hi @adzenith sorry at the moment the plugin only extracts the user defined component fields.  :disappointed: I didn't think to output the component's footprint. It shouldn't be hard to code so I'll add it to this week's update.

:smile: If you don't mind me asking, what do you do with the footprint on BOM? Is it part of your hardware review?

-Ron

**Comment by adzenith** [comment]
We use the footprint for two things, actually. The first is an automated system that takes the BOM and turns it into a Digikey order, and it's used to taking old-style KiCad BOMs (before they moved to the xml output). Some people are still using the old version of KiCad so I was experimenting to see if I could exactly replicate the old output.

The other thing we use the footprint for is our RFQs, to make it easy for our manufacturers to see the sizes of our components.

Thanks so much!

**Comment by HashDefineElectronics** [comment]
Hey @adzenith I've pushed the update to the plugin. It now output the component's footprint. I've used the tag that you posted earlier for the footprint data. ******

Also, the update fixes a bug that cause the plugin to not group certain components.

If you don't mind, could you check if it works for you.

**Comment by adzenith** [comment]
Awesome! That was fast. I'll check it out.

**Comment by adzenith** [comment]
Works great! Thanks so much!
