### ISSUE TITLE
Doesn't run "out of the box" on a mac - with homebrew

### ISSUE THREAD

**Issue by mizraith** [HashDefineElectronics/KiCad_BOM_Wizard#5]
On OS X with homebrew, would not run out of the box.  There are 2 workaround options:

1.   On the Bill of Materials Command Line in KiCad use: /usr/local/bin/node "....KiCad_BOM_Wizard.js"....etc
2.  Edit the top line of the KiCad_BOM_Wizard.js file to read  #!/usr/local/bin/node

**Comment by HashDefineElectronics** [comment]
I'm not sure if this is going to work for everyone else or is its an issue with the script.

Here a mac user whch was find using this path

> /usr/local/bin/node

https://forum.kicad.info/t/kicad-bom-wizard-plugin-with-customisable-output-can-make-html-and-csv-bom/2142/7?u=opticalworm

**Comment by mizraith** [comment]
For whatever reason the original shebang, "#!/usr/bin/env node"  just doesn't work on OS X.  I'm using option #1 above so as not to edit your original source file.
