### ISSUE TITLE
CSV File getting munched vs. HTML

### ISSUE THREAD

**Issue by mizraith** [HashDefineElectronics/KiCad_BOM_Wizard#6]
On Mac OS X Seeing interesting differences between CSV and HTML.  Might be because not every single one of my parts shares identical fields due to legacy parts from prior projects.    

In short, the CSV seems to be running fields together whereas the HTML is not.   

<img width="1083" alt="screen shot 2016-10-11 at 12 48 43 am" src="https://cloud.githubusercontent.com/assets/5092780/19262591/bc881ec4-8f4c-11e6-9ded-d1c8f52ef94f.png">

<img width="1112" alt="screen shot 2016-10-11 at 12 49 30 am" src="https://cloud.githubusercontent.com/assets/5092780/19262595/c1f5ac96-8f4c-11e6-9dca-4529fbb67481.png">

Both CSV and HTML have weird issues with text values as well.  I'm not using any special characters in EESchema...just "10uF", etc.

**Comment by HashDefineElectronics** [comment]
it looks like the CVS template isn't adding the comma between values and footprint. Ill check it out but might need a copy of your xml file.

**Comment by mizraith** [comment]
I can get you a copy of the xml, but would like to keep it off of github (as it effectively is the entire design for this project).  Thoughts on how I can get it to you?

**Comment by HashDefineElectronics** [comment]
I've pushed a fix to the csv template. it was missing the comma that separates the footprint to the value filed
